/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author moham
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    add_drug obj = new add_drug();
    
    
    public Home() {
        initComponents();
        // Set Frame in Middle of Screen
        this.setLocationRelativeTo(null);
        // Rounded Border of Search Text Field
         Border roundedBorder = new LineBorder(new Color(60,64,71), 10, true);
         jsearch.setBorder(roundedBorder);
         obj.fillTable(jTable1 , "");
         
         // To Mark Drug List Button When start 
        jdruglist.setVisible(true);
        jinventory.setVisible(false);
        jdeliveries.setVisible(false);
        jstaff.setVisible(false);
        setcolormainpanel(jPanel3);
        setyellowcolor(jPanel5);
        settextcolor(jLabel3);
        resetTextcolor(jLabel12);
        resetTextcolor(jLabel14);
        resetTextcolor(jLabel13);
        resetcolor(jPanel20);
        resetcolor(jPanel24);
        resetcolor(jPanel22);
        resetcolor(jPanel21);
        resetcolor(jPanel25);
        resetcolor(jPanel23);
        


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel156 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jdruglist = new javax.swing.JPanel();
        jsearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jid_text = new javax.swing.JTextField();
        jprice_text = new javax.swing.JTextField();
        jquantity_text = new javax.swing.JTextField();
        jexp_date = new javax.swing.JTextField();
        jname_text = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jinventory = new javax.swing.JPanel();
        jdeliveries = new javax.swing.JPanel();
        jstaff = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(33, 36, 41));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(60, 64, 71));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pill_70px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 165, 0));
        jLabel2.setText("System");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 70));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 165, 0));
        jLabel4.setText("Pharmacy");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 70));

        jPanel3.setBackground(new java.awt.Color(60, 64, 71));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(167, 166, 164));
        jLabel3.setText("Drug List");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(60, 64, 71));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 366, -1));

        jPanel20.setBackground(new java.awt.Color(60, 64, 71));
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel20MousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(167, 166, 164));
        jLabel12.setText("Inventory");

        jPanel21.setBackground(new java.awt.Color(60, 64, 71));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, -1));

        jPanel24.setBackground(new java.awt.Color(60, 64, 71));
        jPanel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel24MousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(167, 166, 164));
        jLabel14.setText("Deliveries");

        jPanel25.setBackground(new java.awt.Color(60, 64, 71));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel2.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 366, -1));

        jPanel22.setBackground(new java.awt.Color(60, 64, 71));
        jPanel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel22MousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(167, 166, 164));
        jLabel13.setText("Staff");

        jPanel23.setBackground(new java.awt.Color(60, 64, 71));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 366, -1));

        jPanel26.setBackground(new java.awt.Color(60, 64, 71));
        jPanel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel26MousePressed(evt);
            }
        });

        jLabel156.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel156.setForeground(new java.awt.Color(167, 166, 164));
        jLabel156.setText("Logout");

        jPanel27.setBackground(new java.awt.Color(60, 64, 71));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel156)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel156, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 370, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 840));

        jdruglist.setBackground(new java.awt.Color(33, 36, 41));

        jsearch.setBackground(new java.awt.Color(60, 64, 71));
        jsearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jsearch.setForeground(new java.awt.Color(255, 255, 255));
        jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsearchActionPerformed(evt);
            }
        });
        jsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsearchKeyPressed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(60, 64, 71));
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Price", "EXP-Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add_30px.png"))); // NOI18N
        jButton3.setText("  Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_25px.png"))); // NOI18N
        jButton6.setText(" Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete_25px.png"))); // NOI18N
        jButton5.setText("   Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jid_text.setBackground(new java.awt.Color(204, 204, 204));
        jid_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jprice_text.setBackground(new java.awt.Color(204, 204, 204));
        jprice_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jprice_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jprice_textActionPerformed(evt);
            }
        });

        jquantity_text.setBackground(new java.awt.Color(204, 204, 204));
        jquantity_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jquantity_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jquantity_textActionPerformed(evt);
            }
        });

        jexp_date.setBackground(new java.awt.Color(204, 204, 204));
        jexp_date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jname_text.setBackground(new java.awt.Color(204, 204, 204));
        jname_text.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jname_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jname_textActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Search");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EXP-Date");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Quantity");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");

        javax.swing.GroupLayout jdruglistLayout = new javax.swing.GroupLayout(jdruglist);
        jdruglist.setLayout(jdruglistLayout);
        jdruglistLayout.setHorizontalGroup(
            jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdruglistLayout.createSequentialGroup()
                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdruglistLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(jdruglistLayout.createSequentialGroup()
                                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jdruglistLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jsearch, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jdruglistLayout.createSequentialGroup()
                                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jid_text, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(59, 59, 59)
                                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(65, 65, 65)
                                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdruglistLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                        .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jprice_text, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(64, 64, 64)
                                        .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jexp_date, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jdruglistLayout.createSequentialGroup()
                                        .addComponent(jquantity_text, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jdruglistLayout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jdruglistLayout.setVerticalGroup(
            jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdruglistLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jdruglistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jid_text, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jexp_date)
                    .addComponent(jquantity_text)
                    .addComponent(jprice_text))
                .addGap(71, 71, 71)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel1.add(jdruglist, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1050, 840));

        jinventory.setBackground(new java.awt.Color(102, 255, 51));

        javax.swing.GroupLayout jinventoryLayout = new javax.swing.GroupLayout(jinventory);
        jinventory.setLayout(jinventoryLayout);
        jinventoryLayout.setHorizontalGroup(
            jinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jinventoryLayout.setVerticalGroup(
            jinventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        jPanel1.add(jinventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1050, 840));

        jdeliveries.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jdeliveriesLayout = new javax.swing.GroupLayout(jdeliveries);
        jdeliveries.setLayout(jdeliveriesLayout);
        jdeliveriesLayout.setHorizontalGroup(
            jdeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jdeliveriesLayout.setVerticalGroup(
            jdeliveriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        jPanel1.add(jdeliveries, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1050, 840));

        jstaff.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jstaffLayout = new javax.swing.GroupLayout(jstaff);
        jstaff.setLayout(jstaffLayout);
        jstaffLayout.setHorizontalGroup(
            jstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jstaffLayout.setVerticalGroup(
            jstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        jPanel1.add(jstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 1050, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        
        jdruglist.setVisible(true);
        jinventory.setVisible(false);
        jdeliveries.setVisible(false);
        jstaff.setVisible(false);
        setcolormainpanel(jPanel3);
        setyellowcolor(jPanel5);
        settextcolor(jLabel3);
        resetTextcolor(jLabel12);
        resetTextcolor(jLabel14);
        resetTextcolor(jLabel13);
        resetcolor(jPanel20);
        resetcolor(jPanel24);
        resetcolor(jPanel22);
        resetcolor(jPanel21);
        resetcolor(jPanel25);
        resetcolor(jPanel23);

        
    }//GEN-LAST:event_jPanel3MousePressed

   
    
    
    private void jPanel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MousePressed
        // TODO add your handling code here:
        jdruglist.setVisible(false);
        jinventory.setVisible(true);
        jdeliveries.setVisible(false);
        jstaff.setVisible(false);
        setcolormainpanel(jPanel20);
        setyellowcolor(jPanel21);
        settextcolor(jLabel12);
        
        
        resetTextcolor(jLabel3);
        resetTextcolor(jLabel14);
        resetTextcolor(jLabel13);
        
        
        resetcolor(jPanel3);
        resetcolor(jPanel5);
        resetcolor(jPanel24);
        resetcolor(jPanel25);
        resetcolor(jPanel22);
        resetcolor(jPanel23);
    }//GEN-LAST:event_jPanel20MousePressed

    private void jPanel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel22MousePressed
        // TODO add your handling code here:
        
        jdruglist.setVisible(false);
        jinventory.setVisible(false);
        jdeliveries.setVisible(false);
        jstaff.setVisible(true);
        
        
        setcolormainpanel(jPanel22);
        setyellowcolor(jPanel23);
        settextcolor(jLabel13);
        
        resetTextcolor(jLabel3);
        resetTextcolor(jLabel14);
        
        resetcolor(jPanel3);
        resetcolor(jPanel5);
        
        resetcolor(jPanel20);
        resetcolor(jPanel21);
        
        resetcolor(jPanel24);
        resetcolor(jPanel25);
        
        
        
    }//GEN-LAST:event_jPanel22MousePressed

    private void jPanel24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel24MousePressed
        // TODO add your handling code here:
        
        jdruglist.setVisible(false);
        jinventory.setVisible(false);
        jdeliveries.setVisible(true);
        jstaff.setVisible(false);
        
        setcolormainpanel(jPanel24);
        setyellowcolor(jPanel25);
        settextcolor(jLabel14);
        
        resetTextcolor(jLabel3);
        resetTextcolor(jLabel12);
        resetTextcolor(jLabel13);
        
        resetcolor(jPanel3);
        resetcolor(jPanel5);
        
        resetcolor(jPanel20);
        resetcolor(jPanel21);
        
        resetcolor(jPanel22);
        resetcolor(jPanel23);
        
        
        
        
    }//GEN-LAST:event_jPanel24MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MousePressed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new add_drug();
        frame.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    // Update Button
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           try {
             // Connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + "PMS" + "?useSSL=false" , "root", "ahmedroot");
            // Update Data in MySQL
            PreparedStatement ps = con.prepareStatement("UPDATE `pms`.`drug_list` SET `ID` = ?, `name` = ?, `quantity` = ?, `price` = ?, `exp_date` = ? WHERE (`ID` = ?)");
            ps.setString(1,jid_text.getText());
            ps.setString(2,jname_text.getText());
            ps.setString(3,jquantity_text.getText());
            ps.setString(4,jprice_text.getText());
            ps.setString(5,jexp_date.getText());
            ps.setString(6, jid_text.getText());
            // if row selected 
            if(ps.executeUpdate() > 0 )
            {
                 JOptionPane.showMessageDialog(null, "Drug Updated !");
            }
            else
            { JOptionPane.showMessageDialog(null, "Select Drug To Delete !");
}
            
            } catch (Exception e) {
               JOptionPane.showMessageDialog(null, e);

            }
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"ID","Name","Quantity","Price","EXP-Date"}));
        obj.fillTable(jTable1, "");
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/" + "PMS" + "?useSSL=false" , "root", "ahmedroot");
           // Delete From Table 
            PreparedStatement ps = con.prepareStatement("DELETE FROM `pms`.`drug_list` WHERE (`ID` = ?)");
            // Delete By ID of ROW
            int id = Integer.valueOf(jid_text.getText());
            ps.setInt(1,id);
            // if row Selected 
            if (ps.executeUpdate() > 0){JOptionPane.showMessageDialog(null, "Drug Deleted");
            // Delete Text From Text Field after Delete Selected Row 
            jid_text.setText("");
            jname_text.setText("");
            jquantity_text.setText("");
            jprice_text.setText("");
            jexp_date.setText("");
            
            }
            // if row not Selected
            else {JOptionPane.showMessageDialog(null, "Select Drug To Delete");}
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        // Refresh Table After Delete
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"ID","Name","Quantity","Price","EXP-Date"}));
        obj.fillTable(jTable1, "");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jname_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jname_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jname_textActionPerformed

    private void jquantity_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jquantity_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jquantity_textActionPerformed

    private void jprice_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jprice_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jprice_textActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // Get Selected Row
        int rowindex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // Set the Selected row data into Text Field
        jid_text.setText(model.getValueAt(rowindex, 0).toString());
        jname_text.setText(model.getValueAt(rowindex, 1).toString());
        jquantity_text.setText(model.getValueAt(rowindex, 2).toString());
        jprice_text.setText(model.getValueAt(rowindex, 3).toString());
        jexp_date.setText(model.getValueAt(rowindex, 4).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsearchKeyPressed
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null , new Object[]{"ID","Name","Quantity","Price","EXP-Date"}));
        obj.fillTable(jTable1, jsearch.getText());
        
        
        
        
        
        
        
    }//GEN-LAST:event_jsearchKeyPressed

    private void jPanel26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel26MousePressed
        // TODO add your handling code here:
         setVisible(false);
        JFrame frame = new Login();
        frame.setVisible(true);
        
        setcolormainpanel(jPanel26);
        setyellowcolor(jPanel27);
        settextcolor(jLabel156);
        
        resetTextcolor(jLabel3);
        resetTextcolor(jLabel12);
        resetTextcolor(jLabel13);
        resetTextcolor(jLabel14);
        
        resetcolor(jPanel3);
        resetcolor(jPanel5);
        
        resetcolor(jPanel20);
        resetcolor(jPanel21);
        
        resetcolor(jPanel22);
        resetcolor(jPanel23);
        
        resetcolor(jPanel24);
        resetcolor(jPanel25);
        
        
        
        
        
        
        
     
        
        
    }//GEN-LAST:event_jPanel26MousePressed
    
    
    
    void setcolormainpanel(JPanel jPanel)
    {
    jPanel.setBackground(new Color(33,35,41));
    }
    void resetcolor (JPanel jPanel)
    {
    jPanel.setBackground(new Color(60,64,71));
    }
    void setyellowcolor(JPanel jPanel)
    {
    jPanel.setBackground(new Color(255,165,0));
    }
    void settextcolor(JLabel jl)
    {
    jl.setForeground(new Color(255,165,0));
    }
    void resetTextcolor(JLabel j1)
    {
    j1.setForeground(new Color(167,166,164));
    }
               
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                new Home().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JPanel jdeliveries;
    private javax.swing.JPanel jdruglist;
    private javax.swing.JTextField jexp_date;
    private javax.swing.JTextField jid_text;
    private javax.swing.JPanel jinventory;
    private javax.swing.JTextField jname_text;
    private javax.swing.JTextField jprice_text;
    private javax.swing.JTextField jquantity_text;
    private javax.swing.JTextField jsearch;
    private javax.swing.JPanel jstaff;
    // End of variables declaration//GEN-END:variables
}
